Shopify/SkillsShopify/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include( ( 'shopifyapp.urls' , 'shopifyapp') , namespace="shopify" ) ),
    path('user/', include(('userapp.urls', 'userapp'), namespace='userapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

Shopify/shopifyapp/urls.py
from django.urls import path
from shopifyapp.views import IndexPageView , CreateProductView , CreateCategoryView , ViewProduct , EditProduct , DeleteProduct , SearchProduct , ElectronicsView , ClothsView , GetProductByCreatedUser , HomeAppliances

urlpatterns = [
    path('', IndexPageView.as_view(), name='home'),
    path('create-product/', CreateProductView.as_view(), name='create-product'),
    path('create-category/', CreateCategoryView.as_view(), name='create-category'),
    path('view-product/<int:id>/', ViewProduct.as_view(), name='view-product'),
    path('edit-product/<int:id>/', EditProduct.as_view(), name='edit-product'),
    path('delete-product/<int:id>/', DeleteProduct.as_view(), name='delete-product'),
    path('search-product/', SearchProduct.as_view(), name='search-product'),
    path('electronics-product/', ElectronicsView.as_view(), name='electronics-product'),
    path('cloths-product/', ClothsView.as_view(), name='cloths-product'),
    path('home-appliances-product/', HomeAppliances.as_view(), name='home-appliances-product'),
    path('user-product/<int:id>/', GetProductByCreatedUser.as_view(), name='user-product'),
]
 

Shopify/userapp/urls.py
from django.urls import path
from userapp.views import UserRegisterView
from django.contrib.auth import views as  auth_views

urlpatterns = [
    path('register/<str:role>/', UserRegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

 

Shopify/shopifyapp/models.py
from django.db import models
from userapp.models import User

# Create your models here.
class Category (models.Model):
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    discription = models.TextField()
    original_price = models.FloatField()
    discount_percentage = models.IntegerField()
    selling_price = models.FloatField()
    image = models.ImageField(upload_to='media')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey( User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.name}"  
    

Shopify/shopifyapp/forms.py
from django import forms
from shopifyapp.models import Product

class AddProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['name', 'discription', 'original_price' , 'discount_percentage', 'image', 'category']

Shopify/shopifyapp/views.py
from django.shortcuts import render , redirect
from django.views import View
from shopifyapp.models import Category , Product
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddProductForm


# Create your views here.
class IndexPageView(View):

    def get(self, request):
        products = Product.objects.all()
        return render(request, 'shopifyapp/index.html' , context={'products' : products})
    

class CreateProductView(LoginRequiredMixin , View):
    def get(self, request):
        context = {
            'form': AddProductForm()
        }                                                  
        return render(request, 'shopifyapp/add-product.html' , context)
    
    def post(self, request):    
        try :
            form = AddProductForm(request.POST , request.FILES)
            print(request.user)
        
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user  # Assigning the user to the product
                discount_price = instance.original_price * instance.discount_percentage / 100
                selling_price = instance.original_price - discount_price
                instance.selling_price = selling_price
                instance.save()

        except Exception as e :
            print(f'{type(e).__name__} : {e}')

        return redirect('shopify:home')
        

class CreateCategoryView(LoginRequiredMixin , View):
    flag = False
    def get(self, request):
        return render(request, 'shopifyapp/add-category.html')
    
    def post(self, request):
        flag = False
        try :
            category_name = request.POST.get('cname')
            category = Category(name = category_name)
            category.save()
            print("Product Added Successfully")
            flag =True

            return redirect('shopify:home')
        except Exception as e :
            flag =False
            print(f'{type(e).__name__} : {e}')
        return render(request, 'shopifyapp/add-category.html' , {'flag' : flag})
    


class ViewProduct(View) :

    def get(self , request , id):
        print(id)
        product = Product.objects.get(pk=id)
        return render(request , 'shopifyapp/view-product.html' , {'product':product})
    
    
class EditProduct(LoginRequiredMixin , View) :

    def get(self , request , id):
        product = Product.objects.get(pk=id)
        return render(request , 'shopifyapp/edit-product.html' , {'product':product})
    
    def post(self, request , id):    
        try :  
            # Fetching product and category from database
            db_product = Product.objects.get(pk=id)          
                                         
            # Calculation of discount and selling price
            original_price_user = float(request.POST.get("oprice").replace(",", ""))
            discount_percentage_user = float(request.POST.get("dprice").replace(",", ""))
            discount_price = (original_price_user * discount_percentage_user) / 100
            selling_price = original_price_user - discount_price

            # Updating database product object with new values
            db_product.name = request.POST.get("pname")
            db_product.discription = request.POST.get("discription")                                   
            db_product.original_price = original_price_user
            db_product.discount_percentage = discount_percentage_user
            db_product.selling_price = selling_price 
            db_product.image = request.FILES.get("image")

            # Save database product with new changes
            db_product.save()
            print("Product Updated Successfully")

            # Return redirect user to home page 
            return redirect('shopify:home')

        except Exception as e :
            print(f'{type(e).__name__} : {e}')
        return render(request, 'shopifyapp/add-product.html')
    

class DeleteProduct(LoginRequiredMixin , View) :

    def get(self , request , id):
        product = Product.objects.get(pk=id)
        return render(request, 'shopifyapp/delete.html', context={'product': product})
    
    def post(self, request , id):
        product = Product.objects.get(pk=id)
        product.delete()
        return redirect('shopify:home')
    

class SearchProduct(View):

    def post(self, request):
        search = request.POST.get('search')
        search_list = Product.objects.filter(Q(name__icontains=search) | Q(category__name__icontains=search))
        return render(request, 'shopifyapp/searchlist.html', {'search_list': search_list})
    

class ElectronicsView(View):
    def get(self, request):
        product = Product.objects.filter(category__name = 'Electronics')
        print("Fetched Products :", product)
        return render(request , 'shopifyapp/electronics.html', {'product' : product} ) 
    

class ClothsView(View):
    def get(self, request):
        product = Product.objects.filter(category__name = 'Cloths')
        print("Fetched Products :", product)
        return render(request , 'shopifyapp/cloths.html', {'product' : product} ) 
    

class HomeAppliances(View):
    def get(self, request):
        product = Product.objects.filter(category__name = 'Home Appliances')
        print("Fetched Products :", product)
        return render(request , 'shopifyapp/home-appliances.html', {'product' : product} )
    

class GetProductByCreatedUser(LoginRequiredMixin, View):
    def get(self, request, id):
        product_list = Product.objects.filter(user__id=id)

        return render(request , 'shopifyapp/index.html' , context={'products' : product_list})

Shopify/shopifyapp/templates/shopifyapp/add-category.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %}

<title>shopifyapp-add-category</title>

{% endblock %}

{% block body %}

{% if user.is_authenticated %}
{% if user.is_seller %}

<h1>Add Category Here</h1>

<form action="" method="POST"> {% csrf_token %}
    <div class="form-group">
        <label for="name">Product Name</label>
        <input type="text" class="form-control" name="cname" aria-describedby="emailHelp" >
    </div>

    <button type="submit" class="btn btn-primary"> Add Product </button>
</form>

{% endif %}
{% if not user.is_seller %}

<h1>You do not have seller permissions. Please register or switch to a seller account to add products.</h1>
<a href="{% url 'shopify:home' %}" class="btn btn-secondary">Back</a>

{% endif %}
{% endif %}


{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/add-product.html
{% extends 'shopifyapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

<title>shopifyapp-add-product</title>

{% endblock %}

{% block body %}

{% if user.is_authenticated %}
{% if user.is_seller %}

<h1>Add Product Here</h1>

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary"> Add Product </button>
</form>

{% endif %}
{% if not user.is_seller %}

<h1>You do not have seller permissions. Please register or switch to a seller account to add products.</h1>
<a href="{% url 'shopify:home' %}" class="btn btn-secondary">Back</a>

{% endif %}
{% endif %}


{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/cloths.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %}

<title>shopifyapp-index</title>

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-1g {
            font-size: 3.5rem;
        }
    }
</style>


{% endblock %}

{% block body %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About ShopifyApp</h4>
                    <p class="text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The
                        Java | Python | DS Related Stuff !! </p>
                </div>
            </div>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'shopify:create-product' %}" class="btn btn-primary my-2">Add Product</a>
                <a href="{% url 'shopify:create-category' %}" class="btn btn-secondary my-2">Add Product Category</a>
            </p>
            {% endif %}
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                {% for product in product %}

                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="bd-placeholder-img card-img-top" src="{{ product.image.url }}" alt="Thumbnail"
                            width="100%" height="225">

                        <div class="card-body">
                            <h3>{{ product.name }}</h3>
                            <hr>
                            <p> Original Price ₹ : {{ product.original_price }}</p>
                            <p style="color: red;"> Discount Percentage : {{ product.discount_percentage }} %</p>
                            <p> <b> Selling Price ₹ : {{ product.selling_price }} </b></p>
                            <hr>
                            <p class="card-text"> {{ product.discription | truncatechars:20 }} <a
                                    href="{% url 'shopify:view-product' product.id %}">more</a> </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'shopify:view-product' product.id %}"
                                        class="btn btn-sm btn-outline-success"> View </a> &nbsp;
                                    {% if user.is_authenticated %}
                                    {% if user.id == product.user.id %}
                                    {% if user.is_seller %}
                                    <a href="{% url 'shopify:edit-product' product.id %}"
                                        class="btn btn-sm btn-outline-warning"> Edit </a> &nbsp;
                                    <a href="{% url 'shopify:delete-product' product.id %}"
                                        class="btn btn-sm btn-outline-danger"> Delete </a> &nbsp;
                                    {% endif %}
                                    {% endif %}
                                    {% endif %}
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>©SkillsITAcademy | SkillsShopifyApp | SanyuInfotechPvt.Ltd</p>
    </div>
</footer>

{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/electronics.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %}

<title>shopifyapp-index</title>

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-1g {
            font-size: 3.5rem;
        }
    }
</style>


{% endblock %}

{% block body %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About ShopifyApp</h4>
                    <p class="text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The
                        Java | Python | DS Related Stuff !! </p>
                </div>
            </div>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'shopify:create-product' %}" class="btn btn-primary my-2">Add Product</a>
                <a href="{% url 'shopify:create-category' %}" class="btn btn-secondary my-2">Add Product Category</a>
            </p>
            {% endif %}
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                {% for product in product %}

                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="bd-placeholder-img card-img-top" src="{{ product.image.url }}" alt="Thumbnail"
                            width="100%" height="225">

                        <div class="card-body">
                            <h3>{{ product.name }}</h3>
                            <hr>
                            <p> Original Price ₹ : {{ product.original_price }}</p>
                            <p style="color: red;"> Discount Percentage : {{ product.discount_percentage }} %</p>
                            <p> <b> Selling Price ₹ : {{ product.selling_price }} </b></p>
                            <hr>
                            <p class="card-text"> {{ product.discription | truncatechars:20 }} <a
                                    href="{% url 'shopify:view-product' product.id %}">more</a> </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'shopify:view-product' product.id %}"
                                        class="btn btn-sm btn-outline-success"> View </a> &nbsp;
                                    {% if user.is_authenticated %}
                                    {% if user.id == product.user.id %}
                                    {% if user.is_seller %}
                                    <a href="{% url 'shopify:edit-product' product.id %}"
                                        class="btn btn-sm btn-outline-warning"> Edit </a> &nbsp;
                                    <a href="{% url 'shopify:delete-product' product.id %}"
                                        class="btn btn-sm btn-outline-danger"> Delete </a> &nbsp;
                                    {% endif %}
                                    {% endif %}
                                    {% endif %}
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>©SkillsITAcademy | SkillsShopifyApp | SanyuInfotechPvt.Ltd</p>
    </div>
</footer>

{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/home-appliances.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %}

<title>shopifyapp-index</title>

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-1g {
            font-size: 3.5rem;
        }
    }
</style>


{% endblock %}

{% block body %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About ShopifyApp</h4>
                    <p class="text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The
                        Java | Python | DS Related Stuff !! </p>
                </div>
            </div>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'shopify:create-product' %}" class="btn btn-primary my-2">Add Product</a>
                <a href="{% url 'shopify:create-category' %}" class="btn btn-secondary my-2">Add Product Category</a>
            </p>
            {% endif %}
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                {% for product in product %}

                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="bd-placeholder-img card-img-top" src="{{ product.image.url }}" alt="Thumbnail"
                            width="100%" height="225">

                        <div class="card-body">
                            <h3>{{ product.name }}</h3>
                            <hr>
                            <p> Original Price ₹ : {{ product.original_price }}</p>
                            <p style="color: red;"> Discount Percentage : {{ product.discount_percentage }} %</p>
                            <p> <b> Selling Price ₹ : {{ product.selling_price }} </b></p>
                            <hr>
                            <p class="card-text"> {{ product.discription | truncatechars:20 }} <a
                                    href="{% url 'shopify:view-product' product.id %}">more</a> </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'shopify:view-product' product.id %}"
                                        class="btn btn-sm btn-outline-success"> View </a> &nbsp;
                                    {% if user.is_authenticated %}
                                    {% if user.id == product.user.id %}
                                    {% if user.is_seller %}
                                    <a href="{% url 'shopify:edit-product' product.id %}"
                                        class="btn btn-sm btn-outline-warning"> Edit </a> &nbsp;
                                    <a href="{% url 'shopify:delete-product' product.id %}"
                                        class="btn btn-sm btn-outline-danger"> Delete </a> &nbsp;
                                    {% endif %}
                                    {% endif %}
                                    {% endif %}
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>©SkillsITAcademy | SkillsShopifyApp | SanyuInfotechPvt.Ltd</p>
    </div>
</footer>

{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/index.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %}

<title>shopifyapp-index</title>

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-1g {
            font-size: 3.5rem;
        }
    }
</style>


{% endblock %}

{% block body %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About ShopifyApp</h4>
                    <p class="text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The
                        Java | Python | DS Related Stuff !! </p>
                </div>
            </div>
        </div>
    </div>
</header>

<main role="main">
    {% if user.is_authenticated %}
    {% if user.is_seller %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
            <p>
                <a href="{% url 'shopify:create-product' %}" class="btn btn-primary my-2">Add Product</a>
                <a href="{% url 'shopify:create-category' %}" class="btn btn-secondary my-2">Add Product Category</a>
            </p>
        </div>
    </section>
    {% else %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
        </div>
    </section>
    {% endif %}
    {% else %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Shopify</h1>
            <p class="lead text-muted">Skills It Academy Created It's Shopping Website For Student To Purchese The Java
                | Python | DS Related Stuff !!</p>
        </div>
    </section>
    {% endif %}

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                {% for product in products %}

                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="bd-placeholder-img card-img-top" src="{{ product.image.url }}" alt="Thumbnail"
                            width="100%" height="225">

                        <div class="card-body">
                            <h3>{{ product.name }}</h3>
                            <hr>
                            <p> Original Price ₹ : {{ product.original_price }}</p>
                            <p style="color: red;"> Discount Percentage : {{ product.discount_percentage }} %</p>
                            <p> <b> Selling Price ₹ : {{ product.selling_price }} </b></p>
                            <hr>
                            <p class="card-text"> {{ product.discription | truncatechars:20 }} <a
                                    href="{% url 'shopify:view-product' product.id %}">more</a> </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'shopify:view-product' product.id %}"
                                        class="btn btn-sm btn-outline-success"> View </a> &nbsp;
                                    {% if user.is_authenticated %}
                                    {% if user.id == product.user.id %}
                                    {% if user.is_seller %}
                                    <a href="{% url 'shopify:edit-product' product.id %}"
                                        class="btn btn-sm btn-outline-warning"> Edit </a> &nbsp;
                                    <a href="{% url 'shopify:delete-product' product.id %}"
                                        class="btn btn-sm btn-outline-danger"> Delete </a> &nbsp;
                                    {% endif %}
                                    {% endif %}
                                    {% endif %}
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>©SkillsITAcademy | SkillsShopifyApp | SanyuInfotechPvt.Ltd</p>
    </div>
</footer>

{% endblock %}

Shopify/shopifyapp/templates/shopifyapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Shopify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shopify:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shopify:electronics-product' %}">Electronics</a>
          <a class="dropdown-item" href="{% url 'shopify:cloths-product' %}">Cloths</a>
          <a class="dropdown-item" href="{% url 'shopify:home-appliances-product' %}">Home Appliances</a>
        </div>
      </li>

      {% if user.is_authenticated %}

      <li class="nav-item active">
        <form action="{% url 'userapp:logout' %}" method="post">{% csrf_token %}
          <button type="submit" class="btn btn-link nav-link">Logout</button>
        </form>
      </li>

      {% else %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Register
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'userapp:register' 'seller' %}">SELLER</a>
          <a class="dropdown-item" href="{% url 'userapp:register' 'buyer' %}">BUYER</a>
        </div>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'userapp:login' %}">Login <span class="sr-only">(current)</span></a>
      </li>

      {% endif %}


      {% if user.is_authenticated %}      
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shopify:user-product' user.id %}"> User :- {{user.username}} <span class="sr-only">(current)</span></a>
      </li>
      {% endif %}

    </ul>
    <form action="{% url 'shopify:search-product' %}" class="form-inline my-2 my-lg-0" method="post">{% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>